coverage:
    status:
        project:
            default:
                # Basic threshold for your project
                target: 85%
        patch:
            default:
                # Target coverage for the changes in pull requests
                target: 80%
