coverage:
    status:
        project:
            default:
                # Basic threshold for your project
                target: 90%
        patch:
            default:
                # Target coverage for the changes in pull requests
                target: 85%
ignore:
    - "src/simpy/debug"
