name: Code Style Check

on: [push, pull_request]

jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8" # Update as per your project's Python version

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black isort

            - name: Check code style
              run: |
                  make check-style
